/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IntuitionBettingOracle } from "./IntuitionBettingOracle";
export type { UserProfileRegistry } from "./UserProfileRegistry";

    